version: '3.3'

services:
  app:
    build: 
      context: ../
      dockerfile: ./infra/dockerfile
    environment:
      PINATA_API_KEY: "31f084ecf2ec78dc1b8a"
      PINATA_SECRET_KEY: "764895582c9c191cb897e15da6a374372057bd7efed5c6d794ce2c405ad43be1"
    expose:
      - 8080
    ports: 
      - 8080:8080